---
- name: Ejecuta script en localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ejecuta script en localhost
      script: /tmp/prueba.sh
#      ansible.builtin.shell: "sh prueba.sh"
#      args:
#        chdir: "/tmp/"
